import Foundation
import Testing
import GRDB
@testable import Regards

/// Phase 0 migrator smoke test: the v1 schema creates every table + index
/// from ARCHITECTURE.md §7 and a Contact round-trips through the repository
/// without data loss.
struct DatabaseMigratorTests {

    @Test("v1 migration creates every expected table")
    func v1Tables() async throws {
        let db = try DatabaseFactory.makeInMemoryDatabase()
        let tables = try await db.read { db -> Set<String> in
            let sql = """
                SELECT name FROM sqlite_master
                WHERE type = 'table'
                  AND name NOT LIKE 'sqlite_%'
                  AND name NOT LIKE 'grdb_%'
                """
            let names = try String.fetchAll(db, sql: sql)
            return Set(names)
        }
        let expected: Set<String> = [
            "Contact", "ContactGroup", "ReminderWindow",
            "ScheduledReminder", "InteractionLog", "UserProfile",
        ]
        #expect(expected.isSubset(of: tables),
                "missing tables: \(expected.subtracting(tables))")
    }

    @Test("v1 migration creates the indexes §7 requires")
    func v1Indexes() async throws {
        let db = try DatabaseFactory.makeInMemoryDatabase()
        let indexes = try await db.read { db -> Set<String> in
            let names = try String.fetchAll(db,
                sql: "SELECT name FROM sqlite_master WHERE type='index' AND name NOT LIKE 'sqlite_%'")
            return Set(names)
        }
        // Index names are auto-generated by GRDB; we just assert one exists
        // covering each required column pair by querying SQLite's index_list.
        let contactIndexes = try await db.read { db -> [String] in
            try Row.fetchAll(db, sql: "PRAGMA index_list('Contact')").map { $0["name"] as String }
        }
        let reminderIndexes = try await db.read { db -> [String] in
            try Row.fetchAll(db, sql: "PRAGMA index_list('ScheduledReminder')").map { $0["name"] as String }
        }
        #expect(!contactIndexes.isEmpty)
        #expect(!reminderIndexes.isEmpty)
        // Ensure the uniqueness on systemContactRef shows up.
        #expect(indexes.contains(where: { $0.contains("Contact") }))
    }

    @Test("Singleton rows are seeded by the migrator")
    func singletonRowsSeeded() async throws {
        let db = try DatabaseFactory.makeInMemoryDatabase()
        let (windowCount, profileCount) = try await db.read { db -> (Int, Int) in
            let w = try Int.fetchOne(db, sql: "SELECT COUNT(*) FROM ReminderWindow") ?? 0
            let p = try Int.fetchOne(db, sql: "SELECT COUNT(*) FROM UserProfile") ?? 0
            return (w, p)
        }
        #expect(windowCount == 1)
        #expect(profileCount == 1)
    }

    @Test("A Contact round-trips through the GRDB repository")
    func contactRoundTrip() async throws {
        let queue = try DatabaseFactory.makeInMemoryDatabase()
        let repo = GRDBRepositories(dbQueue: queue).contacts

        let original = Contact(
            systemContactRef: "sys-test-1",
            displayName: "Priya Raghavan",
            tracked: true,
            cadenceDays: 14,
            priorityTier: .innerCircle,
            preferredChannel: .whatsapp,
            preferredChannelValue: "+919876543210",
            lastInteractedAt: Date(timeIntervalSince1970: 1_700_000_000),
            notes: "Test notes")

        try await repo.upsert(original)
        let loaded = try await repo.fetch(id: original.id)

        #expect(loaded?.displayName == original.displayName)
        #expect(loaded?.tracked == true)
        #expect(loaded?.cadenceDays == 14)
        #expect(loaded?.priorityTier == .innerCircle)
        #expect(loaded?.preferredChannel == .whatsapp)
        #expect(loaded?.preferredChannelValue == "+919876543210")
        #expect(loaded?.notes == "Test notes")
        #expect(loaded?.lastInteractedAt == original.lastInteractedAt)
    }

    @Test("Reminder can be written and read back, state update persists")
    func reminderRoundTripAndStateUpdate() async throws {
        let queue = try DatabaseFactory.makeInMemoryDatabase()
        let repos = GRDBRepositories(dbQueue: queue)

        let contact = Contact(
            systemContactRef: "sys-test-2",
            displayName: "Mom",
            tracked: true, cadenceDays: 7,
            priorityTier: .innerCircle,
            preferredChannel: .phoneCall, preferredChannelValue: "+14155550134")
        try await repos.contacts.upsert(contact)

        let reminder = ScheduledReminder(
            contactId: contact.id,
            kind: .cadence,
            scheduledFor: Date(timeIntervalSince1970: 1_800_000_000),
            osNotificationId: "iosid-1")
        try await repos.reminders.upsert(reminder)

        let pending = try await repos.reminders.fetchAllPending()
        #expect(pending.count == 1)
        try await repos.reminders.updateState(id: reminder.id, state: .userCaughtUp)
        let pendingAfter = try await repos.reminders.fetchAllPending()
        #expect(pendingAfter.isEmpty)
    }
}
